### ISSUE TITLE
Issue with sklearn dependency in art-fid package

### ISSUE THREAD

**Issue by neverbiasu** [matthias-wright/art-fid#13]
Hello,

I encountered an issue while trying to install the `art-fid` package using pip. The installation process fails due to a deprecated dependency on the `sklearn` package. The error message suggests using `scikit-learn` instead of `sklearn`.

Here is the error message I received:

```bash
Collecting art-fid
  Using cached art_fid-0.0.1-py3-none-any.whl (10 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\kcloud\miniconda3\lib\site-packages (from art-fid) (1.25.2)
Requirement already satisfied: Pillow>=7.1.2 in c:\users\kcloud\miniconda3\lib\site-packages (from art-fid) (10.0.1)
Requirement already satisfied: tqdm>=4.60.0 in c:\users\kcloud\miniconda3\lib\site-packages (from art-fid) (4.65.0) 
Collecting sklearn (from art-fid)
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
     
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
     
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Could you please update the dependencies of the `art-fid` package to use `scikit-learn` instead of `sklearn`? This would help to avoid such installation issues in the future.

My solution is installing with the source code,
```bash
pip install git+https://github.com/matthias-wright/art-fid.git
```
Thank you for your attention to this matter.

**Comment by matthias-wright** [comment]
Hi @neverbiasu, thanks for reaching out!
Sure, would you mind making a PR for this?

**Comment by neverbiasu** [comment]
I'm glad to try it. Wait my PR O(∩_∩)O

**Comment by neverbiasu** [comment]
@matthias-wright I think it was solved by #12 but u should publish it on PyPI, and I have another issues to report
```bash
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<string>", line 1, in <module>
  File "C:\Users\kcloud\miniconda3\envs\constfs\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\kcloud\miniconda3\envs\constfs\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\kcloud\miniconda3\envs\constfs\lib\site-packages\art_fid\art_fid.py", line 9, in <module>
    from torchvision.transforms import Compose, Resize, CenterCrop, ToTensor, Normalize, InterpolationMode
  ...
  File "C:\Users\kcloud\miniconda3\envs\constfs\lib\site-packages\torchvision\transforms\functional.py", line 168, in to_tensor        
    img = torch.from_numpy(np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True))
RuntimeError: Numpy is not available
```
I will make a PR related to this problem.

**Comment by neverbiasu** [comment]
What is more, when I running the command `pip install .` to install the new version, another error occurs.
```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda 23.7.4 requires requests<3,>=2.27.0, but you have requests 2.24.0 which is incompatible.
Successfully installed art-fid-0.0.2 lpips-0.1.4 requests-2.24.0
```
Because the requests is not suitable for the latest conda. I will also include it in PR.

**Comment by matthias-wright** [comment]
Thanks for the PR @neverbiasu !
I just merged it and uploaded the new version to pypi.
